### ISSUE TITLE
Problem with the build

### ISSUE THREAD

**Issue by rigazilla** [preshing/junction-sample#1]
Hi,
I'm trying to use this examples to look into Junction, but I can't build it.

is this sample still valid?

Did this:
```
git clone https://github.com/preshing/junction-sample.git
cd junction-sample/
cmake -G "Eclipse CDT4 - Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug  .
cmake --build 
```

Got this:
```
/home/rigazilla/git/junction-sample/Main.cpp: In function ‘void testMap()’:
/home/rigazilla/git/junction-sample/Main.cpp:14:11: error: ‘ConcurrentMap’ has no member named ‘insert’
     myMap.insert(14, new Foo);
```

Thank you!

**Comment by rigazilla** [comment]
The method insert has been rename in assign.

So seems to me that it's safe to just do do: 
s/insert/assign

**Comment by preshing** [comment]
Yea, you're probably right, I missed that while renaming. Let me take a look.
